/**
 * Trying to keep as much of our code separate from the autogenerated code
 * Karl Palsson <karlp@remake.is> March 2014
 * 
 */

#include <stddef.h>
#include <mosquitto.h>

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

#include "snmp-mqtt-ietfwg.h"
#include "netSnmpIETFWGTable.h"

void mosq_snmp_logger(struct mosquitto *mosq, void *obj, int level, const char *msg) {
	DEBUGMSGTL(("mosquitto", "level: %d, msg: %s\n", level, msg));
}

void mosq_snmp_msg_handler(struct mosquitto *mosq, void *obj, const struct mosquitto_message *msg) {
	DEBUGMSGTL(("mosquitto", "Received message on topic: %s (%d bytes)\n", msg->topic, msg->payloadlen));
	/*
	 * test/ietfwg/<wgname>/update == create/update
	 *   body is json: {chair1="blahblah", chair2="wopwop"}
	 *   missing chairs in the json will be deleted
	 * test/ietfwg/<wgname>/delete = delete (no body required)
	 */
	struct snmp_mqtt_ietfwg_state_ *st = obj;
	char **topics;
	int topic_count;
	mosquitto_sub_topic_tokenise(msg->topic, &topics, &topic_count);
	if (topic_count < 4) {
		printf("not enough topic sections to care: %s is %d\n", msg->topic, topic_count);
		return;
	}

	if (strcmp(topics[3], "delete") == 0) {
		printf("attempting to delete for working group: %s\n", topics[2]);
		netSnmpIETFWGTable_simple_remove(st->ietfwg_tdata, topics[2]);
	} else if (strcmp(topics[3], "update")) {
		printf("attempting to create_update for working group: %s\n", topics[2]);
		// TODO - need to json parse payload here first...
	}
}

void mosq_snmp_setup(struct snmp_mqtt_ietfwg_state_ *st) {
	mosquitto_lib_init();
	
	st->mosq = mosquitto_new(NULL, true, st);
	mosquitto_log_callback_set(st->mosq, mosq_snmp_logger);
	mosquitto_message_callback_set(st->mosq, mosq_snmp_msg_handler);
	mosquitto_connect(st->mosq, "localhost", 1883, 60);
	mosquitto_subscribe(st->mosq, NULL, "test/ietfwg/#", 0);
}

void mosq_snmp_cleanup(struct snmp_mqtt_ietfwg_state_ *st) {
	mosquitto_disconnect(st->mosq);
	mosquitto_destroy(st->mosq);
	mosquitto_lib_cleanup();
}
