/**
 * Trying to keep as much of our code separate from the autogenerated code
 * Karl Palsson <karlp@remake.is> March 2014
 * 
 */

#include <stddef.h>
#include <mosquitto.h>

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

#include "snmp-mqtt-ietfwg.h"

void mosq_snmp_logger(struct mosquitto *mosq, void *obj, int level, const char *msg) {
	DEBUGMSGTL(("mosquitto", "level: %d, msg: %s\n", level, msg));
}

void mosq_snmp_msg_handler(struct mosquitto *mosq, void *obj, const struct mosquitto_message *msg) {
	DEBUGMSGTL(("mosquitto", "Received message on topic: %s (%d bytes)\n", msg->topic, msg->payloadlen));
	/*
	 * test/ietfwg/<wgname>/update == create/update
	 *   body is json: {chair1="blahblah", chair2="wopwop"}
	 *   missing chairs in the json will be deleted
	 * test/ietfwg/<wgname>/delete = delete (no body required)
	 */
}

void mosq_snmp_setup(struct snmp_mqtt_ietfwg_state_ *st) {
	mosquitto_lib_init();
	
	st->mosq = mosquitto_new(NULL, true, NULL);
	mosquitto_log_callback_set(st->mosq, mosq_snmp_logger);
	mosquitto_message_callback_set(st->mosq, mosq_snmp_msg_handler);
	mosquitto_connect(st->mosq, "localhost", 1883, 60);
	mosquitto_subscribe(st->mosq, NULL, "test/ietfwg/#", 0);
}

void mosq_snmp_cleanup(struct snmp_mqtt_ietfwg_state_ *st) {
	mosquitto_disconnect(st->mosq);
	mosquitto_destroy(st->mosq);
	mosquitto_lib_cleanup();
}
