/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */
#ifndef NETSNMPIETFWGTABLE_H
#define NETSNMPIETFWGTABLE_H

/*
 * function declarations 
 */
void init_netSnmpIETFWGTable(void);
void initialize_table_netSnmpIETFWGTable(void);
Netsnmp_Node_Handler netSnmpIETFWGTable_handler;

/*
 * column number definitions for table netSnmpIETFWGTable 
 */
#define COLUMN_NSIETFWGNAME		1
#define COLUMN_NSIETFWGCHAIR1		2
#define COLUMN_NSIETFWGCHAIR2		3
#endif                          /* NETSNMPIETFWGTABLE_H */
